### ISSUE TITLE
Extra "Add Observation" button

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-baseline-calculator#204]
The first time you click on to the Dashboard, there are 2 "Add Observation" buttons. If you change observatories or refresh the page, the extra button goes away. If you click on anything else, like an observation or the user admin page, then come back, the extra button comes back.

**Comment by emcwhirter-usgs** [comment]
This only affects admin users. Normal users do not see the extra button.

**Comment by jmfee-usgs** [comment]
fixed in #212.
