### ISSUE TITLE
"Questions or comments" link broken.

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-baseline-calculator#210]
The "Questions or comments?" link at the bottom of the page is broken.

**Comment by jmfee-usgs** [comment]
This is not an app problem, this is an issue with the geomag site configuration in `HTDOCS/_config.inc.php`.

**Comment by emcwhirter-usgs** [comment]
This would require setting the `$CONTACT_URL` variable, correct?

**Comment by jmfee-usgs** [comment]
This is part of the `$SITE_COMMONNAV` variable:
https://github.com/usgs/geomag-website/blob/master/src/htdocs/_config.inc.php#L19

**Comment by emcwhirter-usgs** [comment]
That appears to be the configuration for the bottom nav only. It looks like `CONTACT_URL` is used for the "Questions or comments?" link at the bottom according to this:
  https://github.com/usgs/hazdev-template/blob/96da7e0b7c96a74bb2a1c296f4e35c2bc0f9b7e0/src/lib/layout.inc.php#L48

**Comment by jmfee-usgs** [comment]
I stand corrected, it's both of those variables.

**Comment by emcwhirter-usgs** [comment]
This appears to be resolved.
